id: 9231fdb79f8c4e648311d3557905c394
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_157-The_Questions_of_the_Kimnara_King_Druma-v2
  language: en
  author: ''
  volume: {}
